version: '3'

services:

  nginx-proxy-mitm:
    build: .
    ports:
      - "8080:8080"
    dns:
      - 127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    labels:
      - "mitmproxy.proxyVirtualHosts=true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  example-one:
    environment:
      VIRTUAL_HOST: example-one.com
    image: nginx:alpine
