version: '3'

services:

  nginx-proxy-mitm:
    build: .
    container_name: "mitm-proxy"
    tty: true
    ports:
      - "8080:8080"
    dns:
      - 127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: "nginx-proxy"
    labels:
      - "mitmproxy.proxyVirtualHosts=true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  example-one:
    container_name: "example-app"
    environment:
      VIRTUAL_HOST: example-one.com
    image: nginx:alpine
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
